# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

# theme = "blowfish"
baseURL = "https://meatybytes.io/"
defaultContentLanguage = "en"

# pluralizeListTitles = "true" # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles

enableRobotsTXT = true
paginate = 10
summaryLength = 0

buildDrafts = false
buildFuture = true

googleAnalytics = "G-0VB1122M0S"

disqusShortname = "meatybytes"

[params.assets]
customCSS = ["css/custom.css"]

[markup]
  [markup.highlight]
    style = "monokai" # Chọn kiểu bạn thích
    lineNos = true    # Hiển thị số dòng

[imaging]
  anchor = 'Center'

[taxonomies]
  tag = "tags"
  category = "categories"
  topic = "topics"
  series = "series"

[sitemap]
  changefreq = 'hourly'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  threshold = 1
  includeNewer = true
  toLower = false

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "categories"
        weight = 100

    [[related.indices]]
        name = "series"
        weight = 50

    [[related.indices]]
        name = "date"
        weight = 10

    [[related.indices]]
      applyFilter = false
      name = 'fragmentrefs'
      type = 'fragments'
      weight = 10
